[General]
background=./assets/background.jpg

primaryColor={{colors.on_background.default.hex}}
accentColor={{colors.primary.default.hex}}
autoColor=true
use24HourClock=false
backgroundColor={{colors.background.default.hex}}
textColor={{colors.on_background.default.hex}}

fontFamily=FlexRounded
fontSize=12
