[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="GoogleSans-Regular"
FontSize="12"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"
HeaderText=""

BackgroundPlaceholder=""
Background="{{image}}"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="{{colors.on_background.default.hex}}"
DateTextColor="{{colors.on_background.default.hex}}"
TimeTextColor="{{colors.on_background.default.hex}}"

FormBackgroundColor="{{colors.surface.default.hex}}"
BackgroundColor="{{colors.surface.default.hex}}"
DimBackgroundColor="{{colors.surface.default.hex}}"

LoginFieldBackgroundColor="{{colors.on_surface.default.hex}}"
PasswordFieldBackgroundColor="#{{colors.on_surface.default.hex}}"
LoginFieldTextColor="{{colors.on_background.default.hex}}"
PasswordFieldTextColor="{{colors.on_background.default.hex}}"
UserIconColor="{{colors.on_background.default.hex}}"
PasswordIconColor="{{colors.on_background.default.hex}}"

PlaceholderTextColor="{{colors.on_surface.default.hex}}"
WarningColor="{{colors.on_background.default.hex}}"

LoginButtonTextColor="{{colors.on_surface.default.hex}}"
LoginButton_backgroundColor="{{colors.surface.default.hex}}"
SystemButtonsIconsColor="{{colors.on_background.default.hex}}"
SessionButtonTextColor="{{colors.on_background.default.hex}}"
VirtualKeyboardButtonTextColor="{{colors.on_background.default.hex}}"

DropdownTextColor="{{colors.on_surface.default.hex}}"
DropdownSelectedBackgroundColor="{{colors.surface.default.hex}}"
DropdownBackgroundColor="{{colors.on_background.default.hex}}"

HighlightTextColor="{{colors.on_surface.default.hex}}"
HighlightBackgroundColor="{{colors.on_background.default.hex}}"
HighlightBorderColor="transparent"

HoverUserIconColor="{{colors.on_surface.default.hex}}"
HoverPasswordIconColor="{{colors.on_surface.default.hex}}"
HoverSystemButtonsIconsColor="{{colors.on_surface.default.hex}}"
HoverSessionButtonTextColor="{{colors.on_surface.default.hex}}"
HoverVirtualKeyboardButtonTextColor="{{colors.on_surface.default.hex}}"

PartialBlur=""
FullBlur="true"
BlurMax=""
Blur=""
HaveFormBackground="false"
FormPosition="center"

VirtualKeyboardPosition="left"
HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="true"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername="Usuário"
TranslatePlaceholderPassword="Senha"
TranslateShowPassword="Mostrar"
TranslateLogin="Entrar"
TranslateLoginFailedWarning="Acesso Não Autorizado"
TranslateCapslockWarning="Capslock Ativado"
TranslateSession=""
TranslateSuspend="Suspender"
TranslateHibernate="Hibernar"
TranslateReboot="Reiniciar"
TranslateShutdown="Desligar"
TranslateVirtualKeyboardButton=""
