add_newline = true

format = """$os$directory """
right_format = """$character$git_branch$git_metrics$git_status$cmd_duration$time"""

[os.symbols]
Arch = "󰣇"
Android = ""

[os]
disabled = false
format = '[](fg:white)[$symbol ](bg:white fg:black)[](fg:white)'

[directory]
home_symbol = "~"
read_only = " "
style = "bg:yellow fg:black"
truncation_length = 3
truncation_symbol = "../"
format = '[](fg:yellow)[ 󰉋 $path ]($style)[](fg:yellow)'

[directory.substitutions]
"Documents" = "󰈔"
"Downloads" = ""

[character]
success_symbol = ""
error_symbol = "[󱎘](fg:red)"

[git_branch]
style = "bg: blue"
symbol = ""
truncation_length = 12
truncation_symbol = ""
format = "[](bold fg:blue)[ $symbol $branch(:$remote_branch)](fg:black bg:blue)"

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = 'bold blue'
format = '[(  $added )(  $deleted )](bg:blue fg:black)'

[git_status]
conflicted = "  ($count) "
ahead = "  ($count) "
behind = "   ($count) "
diverged = "   ($count) "
untracked = "  ($count) "
stashed = "  ($count) "
modified = ""
staged = '  ($count) '
renamed = "  ($count) "
deleted = "  ($count) "
style = "bg: blue"
format = '[($all_status)](bg:blue fg:black)[](fg:blue)'

[cmd_duration]
format = '[](bold fg:white)[ 󰔛 $duration ](bg:white fg:black)[](bold fg:white)'

[time]
disabled = false
time_format = "%R"
format = '[](bold fg:white)[ $time](bg:white fg:black)[](bold fg:white)'
