[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

[mgr]
ratio = [1, 1, 2]
sort_by = "natural"
sort_dir_first = true
show_hidden = true

[opener]
edit = [ { run = 'nvim %s', block = true, desc = "Neovim", for = "unix" } ]
edit-win = [ { run = 'kitty -- nvim %s', orphan = true, desc = "Neovim (Nova Janela)", for = "unix" } ]
open = [ { run = 'xdg-open %s1', desc = "Abrir com XDG" } ]
play = [ { run = 'vlc %s', orphan = true, for = "unix" } ]
pinta = [ { run = 'pinta %s1', orphan = true, desc = "Editar com Pinta" } ]
extract = [ { run = '7z x %s1', block = true, desc = "Extrair aqui" } ]
zip = [ { run = 'for dir in %s; do if [ -d "$dir" ]; then (cd "$(dirname "$dir")" && zip -r "$(basename "$dir")".zip "$(basename "$dir")"); fi; done', block = true, desc = "Zipar com 7z" } ]

[open]
rules = [
	{ url = "*/", use = [ "edit", "edit-win", "open", "zip" ] },

	{ mime = "text/*",  use = [ "edit", "edit-win", "open" ] },
	{ mime = "image/*", use = [ "open", "pinta" ] },
	{ mime = "video/*", use = [ "play", "open" ] },
	{ mime = "audio/*", use = [ "play", "open" ] },
	{ mime = "application/pdf", use = [ "open" ] },
	
	{ mime = "application/zip", use = [ "extract" ] },
	{ mime = "application/x-tar", use = [ "extract" ] },
	{ mime = "application/x-bzip2", use = [ "extract" ] },
	{ mime = "application/x-gzip", use = [ "extract" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract" ] },
	{ mime = "application/x-rar", use = [ "extract" ] },

	{ url = "*", use = [ "edit", "open" ] }
]
