[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[mgr]
ratio = [1, 1, 2]
sort_by = "natural"
sort_dir_first = true
show_hidden = true


[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
play = [{ run = 'vlc "$@"', orphan = true, for = "unix" }]
pinta = [{ run = 'pinta "$@"', detach = true, desc = "Editar com Pinta" }]
extract = [{ run = '7z x "$@"', block = true, desc = "Extrair aqui" }]

