0x{{colors.terminal_normal_black.default.hex_stripped}}
0x{{colors.terminal_bright_black.default.hex_stripped}}
0x{{colors.terminal_normal_red.default.hex_stripped}}
0x{{colors.terminal_bright_red.default.hex_stripped}}
0x{{colors.terminal_normal_green.default.hex_stripped}}
0x{{colors.terminal_bright_green.default.hex_stripped}}
0x{{colors.terminal_normal_yellow.default.hex_stripped}}
0x{{colors.terminal_bright_yellow.default.hex_stripped}}
0x{{colors.terminal_normal_blue.default.hex_stripped}}
0x{{colors.terminal_bright_blue.default.hex_stripped}}
0x{{colors.terminal_normal_magenta.default.hex_stripped}}
0x{{colors.terminal_bright_magenta.default.hex_stripped}}
0x{{colors.terminal_normal_cyan.default.hex_stripped}}
0x{{colors.terminal_bright_cyan.default.hex_stripped}}
0x{{colors.terminal_normal_white.default.hex_stripped}}
0x{{colors.terminal_bright_white.default.hex_stripped}}
