0x{{colors.term1.default.hex_stripped}}
0x{{colors.term2.default.hex_stripped}}
0x{{colors.term3.default.hex_stripped}}
0x{{colors.term4.default.hex_stripped}}
0x{{colors.term5.default.hex_stripped}}
0x{{colors.term6.default.hex_stripped}}
0x{{colors.term7.default.hex_stripped}}
0x{{colors.term9.default.hex_stripped}}
0x{{colors.term10.default.hex_stripped}}
0x{{colors.term12.default.hex_stripped}}
0x{{colors.term13.default.hex_stripped}}
0x{{colors.term14.default.hex_stripped}}
0x{{colors.term15.default.hex_stripped}}
